<?php
return [
    'objects' => 'Vehículos',
    'tracking_objects' => 'Rastreo de vehículos',
    'object_groups' => 'Grupos de vehículos',
    'object_listview' => 'Lista de vehículos',
    'object_history' => 'Historial de vehículos',
    'maximum_of_objects' => 'El número máximo de vehículos disponibles',
    'offline_objects' => 'Vehículos Sin Conexión',
    'create_only_expired_objects' => 'Crear solo vehículos caducados',
    'installation_offline_objects' => 'Instalación de vehículos sin conexión',
    'installation_all_objects' => 'Instalación de Vehículos',
    'advanced' => 'Información',
    'alarm_disarm' => 'Desactivar  alarma',
    'engine_resume' => 'Desbloquear motor',
    'count' => 'Total',
    'stop' => 'Estacionados',
    'move' => 'En Movimiento',
    'expiration_date' => 'Fecha de expiración',
    'forward' => 'Reenvió',
    'forwards' => 'Reenvíos',
    'max_speed' => 'Máxima velocidad',
    'client' => 'Cliente',
    'address' => 'Dirección',
    'do_route_delete' => '¿De verdad quiere eliminar esta ruta? Todos los datos asociados a esta ruta se perderan.',
    'add_device' => 'Agregar dispositivo',
];
